FROM node:11-alpine

ENV PORT 3000
ENV INTERVAL 300000

ADD . /srv/www

WORKDIR /srv/www

RUN npm install --unsafe-perm

EXPOSE 3000

CMD bin/slackin --port $PORT --interval $INTERVAL $SLACK_ORG $SLACK_TOKEN $GOOGLE_CAPTCHA_SECRET $GOOGLE_CAPTCHA_SITEKEY
